CREATE SCHEMA IF NOT EXISTS `parkinglot` ;

CREATE TABLE IF NOT EXISTS `parkinglot`.`PARKING_LOT` (
  `PARKING_LOT_ID` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`PARKING_LOT_ID`),
  UNIQUE INDEX `PARKING_LOT_ID_UNIQUE` (`PARKING_LOT_ID` ASC) VISIBLE);

CREATE TABLE IF NOT EXISTS `parkinglot`.`SLOT` (
  `SLOT_ID` VARCHAR(50) NOT NULL,
  `PARKING_LOT_ID` VARCHAR(50) NOT NULL,
  `SLOT_SEQ_NO` INT NOT NULL,
  `FLOOR_NO` INT NOT NULL,
  `VEHICLE_TYPE` VARCHAR(20) NOT NULL,
  `IS_OCCUPIED` TINYINT NOT NULL,
  PRIMARY KEY (`SLOT_ID`),
  INDEX `PARKING_LOT_ID_idx` (`PARKING_LOT_ID` ASC) VISIBLE,
  CONSTRAINT `PARKING_LOT_ID`
    FOREIGN KEY (`PARKING_LOT_ID`)
    REFERENCES `parkinglot`.`PARKING_LOT` (`PARKING_LOT_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS `parkinglot`.`TICKET` (
  `TICKET_ID` VARCHAR(50) NOT NULL,
  `SLOT_ID` VARCHAR(50) NOT NULL,
  `PARKED_TIME` DATETIME NOT NULL,
  `UNPARKED_TIME` DATETIME,
  `REGISTRATION_NO` VARCHAR(30) NOT NULL,
  `COLOR` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`TICKET_ID`),
  INDEX `SLOT_ID_idx` (`SLOT_ID` ASC) VISIBLE,
  CONSTRAINT `SLOT_ID`
    FOREIGN KEY (`SLOT_ID`)
    REFERENCES `parkinglot`.`SLOT` (`SLOT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);